<?php
namespace App\Test\TestCase\Controller;

use App\Controller\AthletesController;
use Cake\TestSuite\IntegrationTestCase;

/**
 * App\Controller\AthletesController Test Case
 */
class AthletesControllerTest extends IntegrationTestCase
{

    /**
     * Fixtures
     *
     * @var array
     */
    public $fixtures = [
        'app.athletes',
        'app.clubs',
        'app.users',
        'app.genres',
        'app.events'
    ];

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->useHttpServer(true);
        //$this->disableErrorHandlerMiddleware();
    }

    public function testGetMissing()
    {
        //$this->enableCsrfToken();
        //$this->enableSecurityToken();
        //$this->disableErrorHandlerMiddleware();
        $this->get('/markers/not-there');
        $this->assertResponseCode(404);
    }

    /**
     * Test index method
     *
     * @return void
     */
    public function testIndex()
    {
        $this->disableErrorHandlerMiddleware();
        $this->get('/athletes');
        $this->assertResponseOk();
    }

    /**
     * Test view method
     *
     * @return void
     */
    public function testView()
    {
        $this->disableErrorHandlerMiddleware();
        $this->get('/athletes/view/1');
        $this->assertResponseOk();
    }

    /**
     * Test add method
     *
     * @return void
     */
    public function testAdd()
    {
        $this->markTestIncomplete('Not implemented yet.');
    }

    /**
     * Test edit method
     *
     * @return void
     */
    public function testEdit()
    {
        $this->markTestIncomplete('Not implemented yet.');
    }

    /**
     * Test delete method
     *
     * @return void
     */
    public function testDelete()
    {
        $this->markTestIncomplete('Not implemented yet.');
    }
}
